version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: barber-postgres
    environment:
      POSTGRES_USER: thiago
      POSTGRES_PASSWORD: 485201
      POSTGRES_DB: barber
    ports:
      - "5433:5432" 
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: